baseurl = "vignesh1214.github.io"
languageCode = "en-US"
title = "Vignesh Venkateswaran"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Vignesh Venkateswaran"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "vignesh1214"
  Email         = "ven.vignesh@gmail.com"
  Twitter       = "vignesh1214"
  LinkedIn      = "vigneshven"
  Medium        = "vignesh1214"
